backend:
  name: github
  repo: nik09091312/el-oraculo
  branch: main
  site_domain: el-oraculo.pages.dev

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "articulos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - { label: "Imagen destacada", name: "image", widget: "image", required: false }
      - { label: "Resumen / Copete", name: "summary", widget: "text" }
      - { label: "Cuerpo del artículo", name: "body", widget: "markdown" }